#!/bin/bash
# relay-setup.sh — Relay connection setup and health check
#
# Usage: ./scripts/relay-setup.sh <command> [args]
#
# Commands:
#   check              - Check if Relay configuration exists
#   save <base-url>    - Save Relay URL configuration
#   health             - Test connection to Relay MCP server

set -euo pipefail

CONFIG_DIR="${HOME}/.config/revtelligent"
CONFIG_FILE="${CONFIG_DIR}/relay.env"

case "${1:-}" in
  check)
    if [ ! -f "$CONFIG_FILE" ]; then
      echo '{"configured": false, "reason": "No config file found"}'
      exit 0
    fi

    set -a
    source "$CONFIG_FILE"
    set +a

    if [ -z "${RELAY_URL:-}" ]; then
      echo '{"configured": false, "reason": "Relay URL is empty"}'
      exit 0
    fi

    echo "{\"configured\": true, \"url\": \"${RELAY_URL}\", \"mcpUrl\": \"${RELAY_MCP_URL:-not set}\"}"
    ;;

  save)
    BASE_URL="${2:?Usage: relay-setup.sh save <base-url>}"

    # Strip trailing slash
    BASE_URL="${BASE_URL%/}"

    mkdir -p "$CONFIG_DIR"
    cat > "$CONFIG_FILE" << EOF
# Relay Platform Connection
# Generated by relay-setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# MCP tools authenticate via OAuth automatically.
# This file stores the Relay URL for health checks and diagnostics.

RELAY_URL=${BASE_URL}
RELAY_MCP_URL=${BASE_URL}/mcp
EOF
    chmod 600 "$CONFIG_FILE"

    echo "{\"success\": true, \"configFile\": \"${CONFIG_FILE}\", \"url\": \"${BASE_URL}\", \"mcpUrl\": \"${BASE_URL}/mcp\"}"
    ;;

  health)
    if [ ! -f "$CONFIG_FILE" ]; then
      echo '{"healthy": false, "error": "Not configured. Run relay-setup save <url> first."}'
      exit 1
    fi

    set -a
    source "$CONFIG_FILE"
    set +a

    # Check MCP discovery endpoint
    MCP_DISCOVERY_URL="${RELAY_URL}/.well-known/oauth-protected-resource"
    MCP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
      --max-time 10 \
      "$MCP_DISCOVERY_URL" 2>/dev/null || echo "000")

    MCP_OK=false
    if [ "$MCP_STATUS" = "200" ]; then
      MCP_OK=true
    fi

    echo "{\"healthy\": ${MCP_OK}, \"mcp\": {\"reachable\": ${MCP_OK}, \"status\": ${MCP_STATUS}}, \"relayUrl\": \"${RELAY_URL}\"}"
    ;;

  *)
    echo "Usage: relay-setup.sh <check|save|health>"
    echo ""
    echo "Commands:"
    echo "  check              Check if Relay configuration exists"
    echo "  save <base-url>    Save Relay URL configuration"
    echo "  health             Test connection to Relay MCP server"
    exit 1
    ;;
esac
